//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace AL.Core.Data
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ALDbContext : DbContext
    {
        public ALDbContext()
            : base("name=ALDbContext")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<TestTable> TestTables { get; set; }
        public DbSet<CMSColumn> CMSColumns { get; set; }
        public DbSet<CMSCourse> CMSCourses { get; set; }
        public DbSet<CMSCourseWare> CMSCourseWares { get; set; }
        public DbSet<CMSPublish> CMSPublishes { get; set; }
        public DbSet<SysLoginLog> SysLoginLogs { get; set; }
        public DbSet<SysOperationLog> SysOperationLogs { get; set; }
        public DbSet<SysUser> SysUsers { get; set; }
    }
}
