//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace AL.Core.Data
{
    using System;
    using System.Collections.Generic;
    using AL.Component.Tools;
    
    public partial class SysUser:Entity
    {
        public int UserId { get; set; }
        public string LoginName { get; set; }
        public string Password { get; set; }
        public string Name { get; set; }
        public string Available { get; set; }
        public string Mail { get; set; }
        public string Card { get; set; }
        public string Sex { get; set; }
        public string Phone { get; set; }
        public string CellPhone { get; set; }
        public string Address { get; set; }
        public string PostalCode { get; set; }
        public string EduLevel { get; set; }
        public string PwdQuestion { get; set; }
        public string PwdAnswer { get; set; }
        public Nullable<System.DateTime> RegisterDate { get; set; }
        public Nullable<int> CataLogId { get; set; }
        public Nullable<System.DateTime> LastLoginDate { get; set; }
        public Nullable<System.DateTime> Desc0 { get; set; }
        public string Desc1 { get; set; }
        public string Description { get; set; }
        public string Remark1 { get; set; }
        public string Remark2 { get; set; }
        public string Remark3 { get; set; }
        public string Remark4 { get; set; }
        public string Remark5 { get; set; }
        public string Remark6 { get; set; }
        public string Remark7 { get; set; }
        public string Remark8 { get; set; }
        public string Remark9 { get; set; }
        public string PhotoPath { get; set; }
        public string JoinJob { get; set; }
        public string XueLi { get; set; }
        public string DangPai { get; set; }
        public string ZhiWu { get; set; }
        public string JiBie { get; set; }
        public Nullable<int> SFKT { get; set; }
        public Nullable<int> SFTX { get; set; }
    }
}
